### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by autonomygaps** [dennisseidel/highlightpublicnotes-obsidian-plugin#1]
I'm getting a "failed to install" message, repeatedly. I'm running Obsidian 0.11.13 and macOS  11.2.3

<img width="906" alt="Screen Shot 2021-04-12 at 06 43 02" src="https://user-images.githubusercontent.com/48016853/114341622-7eb3b300-9b5a-11eb-8342-bf679ca03b1b.png">

**Comment by dennisseidel** [comment]
Thanks for the info, I look into this in the evening.

**Comment by dennisseidel** [comment]
You should be able to install now. There was a versioning error. I fixed it and validated it. Thank you again for the info :)

**Comment by autonomygaps** [comment]
It's now installed, but each time I select "Update" it remains stuck on version 1.3.0

**Comment by dennisseidel** [comment]
Thanks, the manifest included an old version. I automated the release process, so this can't happen many more :)
