### ISSUE TITLE
Typo in frontmatterAttribute

### ISSUE THREAD

**Issue by leah-ferguson** [dennisseidel/highlightpublicnotes-obsidian-plugin#2]
https://github.com/dennisseidel/highlightpublicnotes-obsidian-plugin/blob/abc6a7de8166c78ad2b809f5a774cec0f692271a/main.ts#L14

`fronmatterAttribute` is throughout. Should this be `frontmatterAttribute`?

**Comment by dennisseidel** [comment]
Hi Leah, thanks that you found that typo 🙏  I fixed in the 1.4.4 version.

**Comment by leah-ferguson** [comment]
Thanks!
