### ISSUE TITLE
Plugin Non-functional In un-customized help vault

### ISSUE THREAD

**Issue by tallguyjenks** [dennisseidel/highlightpublicnotes-obsidian-plugin#4]
Help vault with no other plugins or customizations with plugin defaults:

![image](https://user-images.githubusercontent.com/29872822/127074331-5b18978a-7749-403d-a214-af25708228af.png)

With the desired effect of custom key-val pair to indicate note is public because it's published with the new insiders' update for `publish: true` key-val pair:

|||
|--|--|
|![image](https://user-images.githubusercontent.com/29872822/127074411-19534594-f075-421c-a5e4-392f2b6062ed.png)|![image](https://user-images.githubusercontent.com/29872822/127074447-eb7f03eb-8495-4d56-b41b-1200db795d0b.png)|

@leah-ferguson its not just you, it appears to be non-functional at the moment :(

**Comment by dennisseidel** [comment]
@tallguyjenks Thanks for the detailed bug report 🙏. I added support for Boolean characters in version 1.5.1. Further I clarified in the README that the plugin checks the files "on load". To see the highlighted titlebar you need to reload/open the note after you added the attribute. Does this work now for you?

**Comment by tallguyjenks** [comment]
It now functions as intended! very pleased! thank you :)
